# Generated by Django 3.1.7 on 2021-03-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFD_ML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frauddetectcount',
            name='FalsePos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='frauddetectcount',
            name='NewCust',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='frauddetectcount',
            name='Suspicious',
            field=models.IntegerField(),
        ),
    ]
