# Generated by Django 3.2 on 2021-04-07 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CFD_ML', '0002_auto_20210302_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frauddetectcount',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
